import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/of';
import 'rxjs/add/observable/throw';
import { Http, Response, Headers } from '@angular/http';
import 'rxjs/add/operator/map';
import 'rxjs/add/observable/of';
import 'rxjs/add/observable/throw';
import 'rxjs/add/operator/catch';

import { DeliveryInitValue } from '../components/delivery/delivery.models';
import { Delivery } from '../models/user';

export const MOCK_DELIVERIES = [
  {
    id: 1,
    nombre: 'Argentino',
    direccion: 'Calle 5 nro 1548',
    telefono: '458 715 42',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 2,
    nombre: 'Bar BQ',
    direccion: 'Calle 128 nro 1542',
    telefono: '125 164 48',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 3,
    nombre: 'El galpón de José',
    direccion: 'Calle 44 nro 2365',
    telefono: '(0221) 154 135 48',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 4,
    nombre: 'Espeto Corrido',
    direccion: 'Calle 523 nro 154',
    telefono: '(0221) 15 552 4548',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 5,
    nombre: 'El Rancho de Don Enquique',
    direccion: 'Calle 12 nro 458',
    telefono: '158 111 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 6,
    nombre: 'Los Hermanos',
    direccion: 'Calle 15 nro 458',
    telefono: '258 222 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 7,
    nombre: 'La Sombrilla',
    direccion: 'Calle 10 nro 458',
    telefono: '358 444 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 8,
    nombre: 'Don Quijote',
    direccion: 'Calle 9 nro 458',
    telefono: '222 333 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 9,
    nombre: 'El Palacio de la milanesa',
    direccion: 'Calle 7 nro 458',
    telefono: '777 122 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 10,
    nombre: 'Pizzarella',
    direccion: 'Calle 3 nro 458',
    telefono: '545 654 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 11,
    nombre: 'Allora',
    direccion: 'Calle 2 nro 458',
    telefono: '5454 232 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 12,
    nombre: 'Quito Pizza',
    direccion: 'Calle 8 nro 458',
    telefono: '322 232 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 13,
    nombre: 'Lo de Carlos',
    direccion: 'Calle 2 nro 458',
    telefono: '232 222 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 14,
    nombre: 'Francesco',
    direccion: 'Calle 6 nro 458',
    telefono: '222 232 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 15,
    nombre: 'La Trattoria',
    direccion: 'Calle 1 nro 458',
    telefono: '343 333 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 16,
    nombre: 'Carloncho',
    direccion: 'Calle 2 nro 458',
    telefono: '232 222 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 17,
    nombre: 'Bliss',
    direccion: 'Calle 1 nro 458',
    telefono: '232 465 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 18,
    nombre: 'Hulk',
    direccion: 'Calle 22 nro 458',
    telefono: '232 666 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 19,
    nombre: 'Burguer King',
    direccion: 'Calle 54 nro 458',
    telefono: '223 456 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 20,
    nombre: 'Bacci',
    direccion: 'Calle 34 nro 458',
    telefono: '434 458 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 21,
    nombre: 'Master Pizza',
    direccion: 'Calle 56 nro 458',
    telefono: '343 343 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 22,
    nombre: 'Vizzio',
    direccion: 'Calle 343 nro 458',
    telefono: '232 232 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 23,
    nombre: 'Grido',
    direccion: 'Calle 11 nro 458',
    telefono: '232 2342 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 24,
    nombre: 'Thionis',
    direccion: 'Calle 11 nro 458',
    telefono: '343 333 12',
    descripcion: null,
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: null,
    apellidoAdmin: null,
    telefonoAdmin: null,
    emailAdmin: null,
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
  {
    id: 25,
    nombre: 'Vellezo',
    direccion: 'Calle 22 nro 458',
    telefono: '343 111 12',
    descripcion: 'Heladería',
    especialidades: null,
    horarioApertura: null,
    horarioClausura: null,
    nombreAdmin: 'Maxi',
    apellidoAdmin: 'Navas',
    telefonoAdmin: '232 232 232',
    emailAdmin: 'maxi@asd.com',
    nombreComercial: null,
    apellidoComercial: null,
    telefonoComercial: null,
    emailComercial: null,
  },
];

@Injectable()
export class DeliveriesService {

  constructor(private http: Http) { }

  public getDeliveries(): Observable<any> {
    if (MOCK_DELIVERIES !== null) {
      return Observable.of(MOCK_DELIVERIES);
    }
    return Observable.throw(new Error('Disculpa. Se produjo un error.'));
  }

  public deleteDelivery(deliveryID: number, allDeliveries: Array<any>): Observable<any> {
    if (allDeliveries !== null && deliveryID !== null) {
      return Observable.of(allDeliveries.filter((delivery) => {
        return (delivery.id !== deliveryID);
      }));
    }
    return Observable.throw(new Error('Disculpa. Se produjo un error.'));
  }

  public getDelivery(deliveryID): Observable<Delivery> {
  const mockDelivery = {
      id: null,
      nombre: null,
      direccion: null,
      telefono: null,
      descripcion: null,
      especialidades: null,
      horarioApertura: null,
      horarioClausura: null,
      nombreAdmin: null,
      apellidoAdmin: null,
      telefonoAdmin: null,
      emailAdmin: null,
      nombreComercial: null,
      apellidoComercial: null,
      telefonoComercial: null,
      emailComercial: null,
    };
    if (deliveryID) {
      mockDelivery.id = deliveryID;
      return Observable.of(mockDelivery);
    }
    return Observable.throw(new Error('Disculpa. Se produjo un error.'));
  }

  public createDelivery(delivery): Observable<any> {
    if (delivery) {
      const mockDelivery = {
        id: null,
        nombre: delivery.nombre,
        direccion: delivery.direccion,
        telefono: delivery.telefono,
        descripcion: delivery.descripcion,
        especialidades: delivery.especialidades,
        horarioApertura: delivery.horarioApertura,
        horarioClausura: delivery.horarioClausura,
        nombreAdmin: delivery.nombreAdmin,
        apellidoAdmin: delivery.apellidoAdmin,
        telefonoAdmin: delivery.telefonoAdmin,
        emailAdmin: delivery.emailAdmin,
        nombreComercial: delivery.nombreComercial,
        apellidoComercial: delivery.apellidoComercial,
        telefonoComercial: delivery.emailComercial,
        emailComercial: delivery.emailComercial
      };
      return Observable.of(mockDelivery);
    }
    return Observable.throw(new Error('Disculpa. Se produjo un error.'));
  }

  editDelivery(delivery, deliveryID): Observable<any> {
    if (delivery) {
      return Observable.of(delivery);
    }
    return Observable.throw(new Error('Disculpa. Se produjo un error.'));
  }
}
